FROM node:16-alpine

WORKDIR /app

COPY ./package.json ./package-lock.json  ./
COPY ./tsconfig.json ./tsconfig.build.json ./
COPY ./src ./src

RUN npm install

ENV TZ=Asia/Seoul

EXPOSE 3000

CMD npm run start:dev