### id 로 게시글 조회하기
GET http://localhost:3000/post/1

### 게시글 목록 조회하기
GET http://localhost:3000/post?offset=0&limit=5

### 제목으로 게시글 목록 조회하기
GET http://localhost:3000/post?title=ORM&offset=0&limit=5

### 게시글 생성 하기
POST http://localhost:3000/post
Content-Type: application/json

{
  "input": {
    "title": "테스트 게시글입니다",
    "content": "테스트 게시글입니다.",
    "createdBy": "1"
  }
}

### 게시글 수정하기
PATCH http://localhost:3000/post/1
Content-Type: application/json

{
  "input": {
    "title": "테스트 게시글입니다",
    "content": "테스트 게시글입니다.",
    "updatedBy": "1"
  }
}

### 게시글 삭제하기
DELETE http://localhost:3000/post/1