### 유저 생성 하기
POST http://localhost:3000/user
Content-Type: application/json

{
  "input": {
    "email": "test123@gmail.com",
    "password": "1234",
    "nickname": "newwwbi"
  }
}

### id 로 유저 조회하기
GET http://localhost:3000/user/1

### 유저 정보 수정하기
PATCH http://localhost:3000/user/1
Content-Type: application/json

{
  "input": {
    "nickname": "newbi"
  }
}

### 유저 정보 삭제하기
DELETE http://localhost:3000/user/1

### 유저가 댓글 단 게시글 목록 조회하기
GET http://localhost:3000/user/1/comment-post?offset=0&limit=5

### 유저 설정 정보 조회하기
GET http://localhost:3000/user/1/setting

### 유저 설정 정보 수정하기
PATCH http://localhost:3000/user/1/setting
Content-Type: application/json

{
  "input": {
    "receiveNewCommentAlarm": false,
    "receivePromotionAlarm": false
  }
}

### 게시글을 즐겨찾기 목록에 추가하기
POST http://localhost:3000/user/1/favorite-post
Content-Type: application/json

{
  "input": {
    "postId": "1"
  }
}

### 게시글을 즐겨찾기 목록에서 삭제하기
DELETE http://localhost:3000/user/1/favorite-post
Content-Type: application/json

{
  "input": {
    "postId": "1"
  }
}

### 유저가 즐겨찾기 목록에 추가한 게시글 목록 조회하기
GET http://localhost:3000/user/1/favorite-post?offset=0&limit=5